title: Mohannad Faihan Otaibi
email: "mohannad.otaibi@gmail.com"
description: "The Geek you wanna talk to about technology and stuff.. I do web and I'm in looove with change..! I will challenge your intelligence #Saudi, #American, #Aramcoan, #xKFUPMer, #Comبuتer_geeك, #MsLkjy, #M5_wAjD_5rBaN, #Enfj, #Married, #Father, #8ies, #Tabs-Team"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.mohannadotaibi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bufai7an
github_username:  mo9a7i

repository: "mohannadotaibi/mohannadotaibi.com"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
favicon_grabber: "https://besticon-demo.herokuapp.com/icon?size=80..120..200&url="
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
