title: Mohannad Faihan Otaibi
email: "mohannad.otaibi@gmail.com"
description: Techno-maniac, love change, Founder of @Hardlayers and @6degz, CTO of @promoefficiency
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.mohannadotaibi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bufai7an
github_username:  mo9a7i

repository: "mohannadotaibi/mohannadotaibi.com"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
