title: Mohannad Faihan Otaibi
email: "mohannad.otaibi@gmail.com"
description: "The Geek you wanna talk to about technology and stuff #Saudi, #xKFUPMer, #Comبuتer_geeك, #MsLkjy, #M5_wAjD_5rBaN, #Enfj, #Married, #Father, #8ies, #Tabs-Team"
baseurl: "/" 
url: "https://mohannadotaibi.com" 
twitter_username: bufai7an
github_username:  mo9a7i

repository: "mohannadotaibi/mohannadotaibi.com"

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
favicon_grabber: "https://favicon.mohannad-otaibi.workers.dev/?url="

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules